---
language: python
services: docker

env:
  global:
    - ROLE_NAME: odr_mmbtools
  matrix:
    - MOLECULE_DISTRO: debian-10
    - MOLECULE_DISTRO: debian-sid
    - MOLECULE_DISTRO: ubuntu-18.04
    - MOLECULE_DISTRO: ubuntu-20.04

cache:
  directories:
    - $HOME/.cache/pre-commit

install:
  - pip3 install -r requirements.txt

script:
  - export ANSIBLE_STRATEGY=mitogen_linear
  - export ANSIBLE_STRATEGY_PLUGINS=${VIRTUAL_ENV}/lib/python${TRAVIS_PYTHON_VERSION}/site-packages/ansible_mitogen/plugins/strategy
  - pre-commit run -c .travis-pre-commit-config.yaml -a
  - molecule --version
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
