---
language: python
services: docker

env:
  global:
    - ROLE_NAME: odr_mmbtools
  matrix:
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: ubuntu1804

install:
  - pip3 install --quiet --requirement requirements.txt

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
