---
language: python
services: docker

env:
  global:
    - ROLE_NAME: odr_mmbtools
  matrix:
    - MOLECULE_DISTRO: debian-10
    - MOLECULE_DISTRO: debian-sid
    - MOLECULE_DISTRO: ubuntu-18.04
    - MOLECULE_DISTRO: ubuntu-20.04

cache:
  directories:
    - $HOME/.cache/pre-commit

jobs:
  include:
    - name: lint with pre-commit
      script:
        - pip3 install pre-commit
        - pre-commit run -c .travis-pre-commit-config.yaml -a

script:
  - |
    if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(.md)|(.pdf)'
    then
      echo "Only doc files were updated, not running the CI."
      exit
    fi
  - pip3 install -r requirements.txt
  - export ANSIBLE_STRATEGY=mitogen_linear
  - export ANSIBLE_STRATEGY_PLUGINS=${VIRTUAL_ENV}/lib/python${TRAVIS_PYTHON_VERSION}/site-packages/ansible_mitogen/plugins/strategy
  - molecule --version
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
