---
language: python
services: docker

env:
  global:
    - ROLE_NAME: odr_mmbtools
    - DRIVER_NAME: docker
  matrix:
    - MOLECULE_DISTRO: debian-10
    - MOLECULE_DISTRO: debian-sid
    - MOLECULE_DISTRO: ubuntu-18.04
    - MOLECULE_DISTRO: ubuntu-20.04
    - MOLECULE_DISTRO: ubuntu-20.10

before_install:
  - |
    if ! git diff --name-only HEAD^ | grep -vE '(.md)|(.pdf)'
    then
      echo "Only doc files were updated, not running the CI."
      exit
    fi

cache:
  directories:
    - $HOME/.cache/pre-commit

jobs:
  include:
    - name: lint with pre-commit
      install: skip
      before_install: skip
      script:
        - pip install pre-commit
        - pre-commit run -c .travis-pre-commit-config.yaml -a

script:
  - export ANSIBLE_STRATEGY=mitogen_linear
  - export ANSIBLE_STRATEGY_PLUGINS=${VIRTUAL_ENV}/lib/python${TRAVIS_PYTHON_VERSION}/site-packages/ansible_mitogen/plugins/strategy
  - molecule --version
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
