---
language: python
services: docker

env:
  global:
    - ROLE_NAME: odr_mmbtools
  matrix:
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: ubuntu1804

install:
  - pip3 install -r requirements.txt

script:
  - export ANSIBLE_STRATEGY=mitogen_linear
  - export ANSIBLE_STRATEGY_PLUGINS=${VIRTUAL_ENV}/lib/python${TRAVIS_PYTHON_VERSION}/site-packages/ansible_mitogen/plugins/strategy
  - molecule --version
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
