---
- name: install required packages (ODR-AudioEnc)
  apt:
    state: present
    name:
      - automake
      - build-essential
      - git
      - jackd2
      - libasound2
      - libasound2-dev
      - libjack-jackd2-dev
      - libtool
      - libvlc-dev
      - libzmq3-dev
      - libzmq5
      - vlc-data
      - vlc-plugin-base

- name: install required packages (ODR-PadEnc)
  apt:
    state: present
    name:
      - libmagickwand-dev

- name: install required packages (ODR-EncoderManager)
  apt:
    state: present
    name:
      - python3-cherrypy3
      - python3-jinja2
      - python3-serial
      - python3-pysnmp4
      - supervisor

- name: install required packages (ODR-DabMux)
  apt:
    state: present
    name:
      - automake
      - build-essential
      - libboost-system-dev
      - libcurl4-openssl-dev
      - libzmq5-dev
