---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install required packages (ODR-AudioEnc)
  ansible.builtin.apt:
    state: present
    name:
      - automake
      - build-essential
      - git
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-ugly
      - jackd2
      - libasound2
      - libasound2-dev
      - libgstreamer-plugins-bad1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer1.0-dev
      - libjack-jackd2-dev
      - libtool
      - libvlc-dev
      - libzmq3-dev
      - libzmq5
      - vlc-data
      - vlc-plugin-base

- name: Install required packages (ODR-PadEnc)
  ansible.builtin.apt:
    state: present
    name:
      - libmagickwand-dev

- name: Install required packages (ODR-DabMux)
  ansible.builtin.apt:
    state: present
    name:
      - automake
      - build-essential
      - libboost-system-dev
      - libcurl4-openssl-dev
      - libzmq5-dev
