---
- name: include task requirements.yml
  include_tasks: requirements.yml

- name: clone fdk-acc repo (ODR version)
  git:
    repo: 'https://github.com/Opendigitalradio/fdk-aac'
    dest: /opt/fdk-aac
    version: "{{ fdk_acc_tag }}"
  notify: compile and install fdk-acc

- name: clone ODR-AudioEnc repo
  git:
    repo: 'https://github.com/Opendigitalradio/ODR-AudioEnc'
    dest: /opt/ODR-AudioEnc
    version: "{{ ODR_AudioEnc_tag }}"
  notify: compile and install ODR_AudioEnc

- name: clone ODR-PadEnc repo
  git:
    repo: 'https://github.com/Opendigitalradio/ODR-PadEnc'
    dest: /opt/ODR-PadEnc
    version: "{{ ODR_PadEnc_tag }}"
  notify: compile and install ODR_PadEnc

- name: create odr user
  user:
    name: odr
    shell: /bin/sh
    comment: odr
    state: present
    groups: dialout,audio

- name: clone ODR-EncoderManager repo
  git:
    repo: 'https://github.com/fauust/ODR-EncoderManager'
    dest: /opt/ODR-EncoderManager
    version: "{{ ODR_EncoderManager_tag }}"
  notify: set /opt/ODR-EncoderManager permissions

- name: clone ODR-DabMux repo
  git:
    repo: 'https://github.com/Opendigitalradio/ODR-DabMux'
    dest: /opt/ODR-DabMux
    version: "{{ ODR_DabMux_tag }}"
  notify: compile and install ODR_DabMux
