---
- name: compile and install ODR_AudioEnc
  ansible.builtin.shell: |
    ./bootstrap
    ./configure --enable-alsa --enable-jack --enable-vlc
    make -j$(nproc)
    make install
  args:
    chdir: /opt/ODR-AudioEnc

- name: compile and install ODR_PadEnc
  ansible.builtin.shell: |
    ./bootstrap
    ./configure
    make -j$(nproc)
    make install
  args:
    chdir: /opt/ODR-PadEnc

- name: compile and install ODR_DabMux
  ansible.builtin.shell: |
    ./bootstrap.sh
    if arch | grep -q arm; then
      ./configure --with-boost-libdir=/usr/lib/arm-linux-gnueabihf
    else
      ./configure
    fi
    make -j$(nproc)
    make install
  args:
    chdir: /opt/ODR-DabMux
