---
driver:
  name: podman
platforms:
  - name: instance
    image: "ghcr.io/fauust/docker-ansible:${MOLECULE_DISTRO:-debian-11}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    override_command: false
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_DISPLAY_OK_HOSTS: "false"
    ANSIBLE_DISPLAY_SKIPPED_HOSTS: false
    ANSIBLE_FORCE_COLOR: true
    ANSIBLE_GATHERING: explicit
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: testinfra
scenario:
  test_sequence:
    - create
    - converge
    - idempotence
    - verify
