---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
    yamllint . -c molecule/default/yamllint.config
    ansible-lint
    flake8
platforms:
  - name: instance
    image: "fauust/docker-systemd-${MOLECULE_DISTRO:-debian10}:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_GATHERING: explicit
    ANSIBLE_FORCE_COLOR: true
    ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3
verifier:
  name: testinfra
