---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: instance
    image: "fauust/docker-ansible:${MOLECULE_DISTRO:-debian-10}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
provisioner:
  name: ansible
  env:
    ANSIBLE_GATHERING: explicit
    ANSIBLE_FORCE_COLOR: true
    ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3
verifier:
  name: testinfra
