---
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yaml-lint.yml
platforms:
  - name: instance
    image: "fauust/docker-systemd-${MOLECULE_DISTRO:-debian10}:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_GATHERING: explicit
    ANSIBLE_FORCE_COLOR: true
    ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
scenario:
  name: default
