---
name: molecule

on:
  push:
  pull_request:
  # schedule:
  #   - cron: "0 5 * * 2"

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - ubuntu-18.04
          - ubuntu-20.04
          - ubuntu-21.04
          - ubuntu-22.04
          - debian-10
          - debian-11
          - debian-sid
        playbook:
          - converge.yml

    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: |
          make install
        # This is necessary on GH Actions to allow running systemd in rootless containers
        # see: https://github.com/actions/virtual-environments/issues/3536
        # see: https://github.com/ansible-community/molecule/discussions/3155
      - name: Start systemd user service
        run: |
          loginctl enable-linger $(whoami)
          sleep 1
      - name: Run molecule
        run: molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ${{ matrix.distro }}
          MOLECULE_PLAYBOOK: ${{ matrix.playbook }}
